### ISSUE TITLE
Name for this repo?

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#11]
@jhenaoz @Thormod @mikicho 

What is your preferred name? My ideas, feel free to add:

- The art of integration tests
- Microservice testing
- Integration tests A-Z
- Modern integration tests
- Your idea?

**Comment by mikicho** [comment]
node-integration-best-practices

**Comment by goldbergyoni** [comment]
@mikicho 

That name worked for me in the past:) I need few days to absorb it.

Isn't **node**-integration-tests-best-practices better?

**Comment by mikicho** [comment]
It's better
