### ISSUE TITLE
Why mark `async` in the callback of `beforeAll`?

### ISSUE THREAD

**Issue by nyngwang** [testjavascript/nodejs-integration-tests-best-practices#145]
https://github.com/testjavascript/nodejs-integration-tests-best-practices/blob/c49a9938d1fc2b8ab6505708ff824d4779c95fcf/example-application/test/basic-tests.test.js#L11

As title. Won't this cause a warning? If this would cause a warning then should I take it as best practice :/ ?

**Comment by rluvaton** [comment]
You're absolutely right, you shouldn't use `done` here, thank you.

A PR is welcome 🤗
