### ISSUE TITLE
📰 October - Catch-up

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#16]
@jhenaoz @Thormod @mikicho 

Dear collaborator, This is just a catch-up summary to help busy people follow and chime-in:

- We have a tasks list for everyone, see the issues 
- @mikicho Created amazing performance research on the impact of RAM folder. In Linux and Windows we see 3x improvement, in Mac it's slower, now investigating why
- @goldbergyoni created the first recipe under 'various-receipes/authentication', I suggest you take a 5min look to see how a recipe can look like and approach the main-example instead of duplicating the API
- How to progress - We can just work async, each at its own pace. Maybe having some weekend coding party, 2-3 hours, can bring a great boost? ❓
- Small tasks that you might pick:
* Create a simple CI for this repo
* Create a Swagger for this API. Later on or now, we can create a recipe that tests our Swagger!, kind of minimal contract test. [See jest-openapi, it's really cool and nice drill](https://www.npmjs.com/package/jest-openapi)
* Create a recipe for memory leakage, see [leakage ](https://www.npmjs.com/package/leakage)
* Seed two large tables like countries list. This will make our examples more realistic as real world project sometime have to seed large data
* Clean up data on global afterAll - There are various approaches for this, some are faster than others (e.g. purge vs drop schema vs cascading delete)

**Comment by mikicho** [comment]
> Create a simple CI for this repo

Which tool do you have in mind? CircleCI? Travis? GitLab? 
I'm less familiar with those (I'm working with Jenkins) but this sounds like a good opportunity.
What tool do you recommend?

**Comment by goldbergyoni** [comment]
@Thormod and I usually work with CircleCI but maybe it's an opportunity for all of us to get into GitHub actions (which will dominate this market soon)

p.s. You are on the most challenging task right now, perf optimization, @Thormod and I can take this or at least let's split the work
