### ISSUE TITLE
sinon.sandbox is obsolete, we can use sinon as-is

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#28]
Our tests currently use sinon.createSandbox to isolate test doubles between the tests. However, starting from a recent version, sinon is by default sandboxed so we can use is as-is and remove the sandbox usage.

Before picking this issue, it's recommended to have a short tech planning chat here and only then upon sync to get up to speed.

**Comment by DanielGluskin** [comment]
do you mean to remove: sinonSandbox = sinon.createSandbox(), and replace **sinonSandbox** with **sinon**?
