### ISSUE TITLE
Deferring our weekendthon in a bit

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#33]
@jhenaoz @mikicho @Thormod 

I have a suggestion to defer the weekenthon in 3 weeks, here's why:

- I should have a work vacation on January 1st week, I can then spend 1-2 full days on bringing it really close to release and then in our Weekendthon we can finalize a version in hours
- A new developer, Daniel @DanielGluskin, is joining our forces 💪, welcome Daniel! It will take him 1-2 weeks to get up to speed probably

I would propose Friday January 7th or 14th + Sunday 9th or 16th, each meeting 2 hours, gonna be fun and insightful.

WDYT?

**Comment by DanielGluskin** [comment]
Hey all, nice to meet! I'm fine with both dates. GL.
