### ISSUE TITLE
Swagger test - Ensure that the API response conforms to the OpenAPI spec

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#49]

**Comment by DanielGluskin** [comment]
@goldbergyoni @mikicho 

[what do you think?](https://github.com/testjavascript/nodejs-integration-tests-best-practices/tree/openapi-contract-test)

**Comment by goldbergyoni** [comment]
@DanielGluskin We have this! 🔥
