### ISSUE TITLE
More isolation scenarios

### ISSUE THREAD

**Issue by goldbergyoni** [testjavascript/nodejs-integration-tests-best-practices#68]
We could show even better how to simulate the real-world chaos in a lab by showing the following tests:

// ❌ Anti-Pattern: We didn't test the scenario where the mailer does not reply (timeout)
// ❌ Anti-Pattern: We didn't test the scenario where the mailer reply slowly (delay)
// ❌ Anti-Pattern: We didn't test the scenario of occasional one-time response failure which can be mitigated with a retry

**Comment by mikicho** [comment]
> // ❌ Anti-Pattern: We didn't test the scenario where the mailer reply slowly (delay)

Why should we test it?

**Comment by goldbergyoni** [comment]
I guess this was asked before we discussed in via Whatsapp
